/* automatically generated by rust-bindgen 0.64.0 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct InitApp {
    pub title: *const ::std::os::raw::c_char,
}
#[test]
fn bindgen_test_layout_InitApp() {
    const UNINIT: ::std::mem::MaybeUninit<InitApp> = ::std::mem::MaybeUninit::uninit();
    let ptr = UNINIT.as_ptr();
    assert_eq!(
        ::std::mem::size_of::<InitApp>(),
        8usize,
        concat!("Size of: ", stringify!(InitApp))
    );
    assert_eq!(
        ::std::mem::align_of::<InitApp>(),
        8usize,
        concat!("Alignment of ", stringify!(InitApp))
    );
    assert_eq!(
        unsafe { ::std::ptr::addr_of!((*ptr).title) as usize - ptr as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(InitApp),
            "::",
            stringify!(title)
        )
    );
}
extern "C" {
    pub fn c_start_application(initApp: *const InitApp) -> ::std::os::raw::c_int;
}
